[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[window.padding]
x = 10
y = 5

[window]
decorations = "buttonless"

[general]
live_config_reload = true
import = ["~/.config/alacritty/colors/rootloops.toml"]
