add_newline = false

format = """
$character\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python """

[character]
success_symbol = "[➜](bright-green)"
error_symbol = "[➜](bright-red)"
vimcmd_symbol = "[󰕷](bright-green)"

[directory]
format = "[$path]($style)"
truncation_length = 1

[git_branch]
format = ' git:\([$branch]($style)\)'
style = "bright-red"

[git_status]
format = '[[$all_status$ahead_behind]($style)]($style)'
style = "218"
conflicted = "x"
untracked = "*"
modified = ""
staged = "+"
renamed = ""
deleted = ""
stashed = "≡"
ahead = "⇡"
behind = "⇣"
up_to_date = ""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[python]
format = "[$virtualenv]($style)"
style = "bright-black"
