add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$character"""

[character]
success_symbol = "[❯](bright-green)"
error_symbol = "[❯](bright-red)"
vimcmd_symbol = "[❮](bright-green)"

[git_branch]
format = 'git:\([$branch]($style)\)'
style = "bright-red"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
