vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "chiefdog"

-- stylua: ignore
local c = {
  transparent = "none",
  bg          = "#101010",
  comment     = "#444444",
  text        = "#b0b0b0",
  keyword     = "#777777",
  definition  = "#ffffff",
  -- string      = "#86CD82",
  string      = "#ffffff",
  constant    = "#d9ba73",
  cursor      = "#272727",
  selection   = "#222E58",
  search      = "#333333",
  error       = "#ff7676",
  hint        = "#2e2e2e",
  add         = "#26332c",
  delete      = "#332626",
  change      = "#262e33",
}

-- stylua: ignore
local groups = {
  Normal       = { bg = c.bg, fg = c.text },
  NormalFloat  = { bg = c.bg, fg = c.text },
  FloatBorder  = { bg = c.bg, fg = c.comment },
  Cursor       = { bg = "#ffffff", fg = c.bg },
  CursorLine   = { bg = c.cursor },
  CursorLineNr = { fg = c.definition, bold = true },
  LineNr       = { fg = c.comment },
  StatusLine   = { bg = c.cursor, fg = c.text },
  StatusLineNC = { bg = c.bg, fg = c.comment },
  StatusLineTerm = { bg = c.cursor, fg = c.text },
  StatusLineTermNC = { bg = c.bg, fg = c.comment },
  WinBar       = { bg = c.bg, fg = c.text, bold = true },
  WinBarNC     = { bg = c.bg, fg = c.comment },
  WinSeparator = { fg = c.comment },
  Pmenu        = { bg = c.cursor, fg = c.text },
  PmenuSel     = { bg = c.comment, fg = c.definition, bold = true },
  PmenuThumb   = { bg = c.text },
  Visual       = { bg = c.selection },
  Search       = { bg = c.constant, fg = c.bg },
  IncSearch    = { link = "Search" },
  CurSearch    = { link = "Search" },
  MatchParen   = { fg = c.definition, bold = true, underline = true },
  NonText      = { fg = c.cursor },
  EndOfBuffer  = { fg = c.bg },
  Question     = { fg = c.constant },
  MoreMsg      = { fg = c.constant },
  ErrorMsg     = { fg = c.error },
  WarningMsg   = { fg = c.constant },
  ModeMsg      = { fg = c.constant },
  QuickFixLine = { fg = c.definition, underline = true },
  qfLineNr     = { fg = c.comment },

  -- Syntax
  Keyword      = { fg = c.keyword },
  Conditional  = { link = "Keyword" },
  Repeat       = { link = "Keyword" },
  Label        = { link = "Keyword" },
  Exception    = { link = "Keyword" },
  Statement    = { link = "Keyword" },
  Operator     = { link = "Keyword" },
  Delimiter    = { fg = c.definition },
  Type         = { link = "Keyword" },
  Structure    = { link = "Keyword" },
  Identifier   = { fg = c.text },
  PreProc      = { link = "Keyword" },
  Include      = { link = "Keyword" },
  Define       = { link = "Keyword" },
  PreCondit    = { link = "Keyword" },
  StorageClass = { link = "Keyword" },
  Typedef      = { link = "Keyword" },
  Tag          = { link = "Keyword" },
  Function     = { fg = c.definition, bold = true },
  Title        = { fg = c.definition, bold = true },
  String       = { fg = c.string },
  Character    = { link = "String" },
  Number       = { fg = c.keyword },
  Boolean      = { fg = c.constant },
  Float        = { fg = c.constant },
  Constant     = { fg = c.constant },
  Macro        = { fg = c.constant },
  Comment      = { fg = c.comment, italic = true },
  Todo         = { fg = c.bg, bg = c.constant, bold = true },
  Special      = { fg = c.text },
  SpecialChar  = { link = "Special" },
  SpecialComment = { link = "Comment" },
  Underlined   = { underline = true },
  Error        = { fg = c.error },
  Debug        = { fg = c.constant },

  -- Treesitter
  ["@function"]              = { link = "Function" },
  ["@function.call"]         = { fg = c.text },
  ["@function.builtin"]      = { fg = c.text },
  ["@function.macro"]        = { link = "Macro" },
  ["@function.method"]       = { link = "Function" },
  ["@function.method.call"]  = { fg = c.text },

  ["@keyword"]               = { link = "Keyword" },
  ["@keyword.function"]      = { link = "Keyword" },
  ["@keyword.return"]        = { fg = c.definition },
  ["@keyword.conditional"]   = { link = "Conditional" },
  ["@keyword.exception"]     = { link = "Exception" },
  ["@keyword.import"]        = { link = "Include" },
  ["@keyword.operator"]      = { link = "Operator" },
  ["@operator"]              = { link = "Operator" },
  ["@punctuation"]           = { link = "Keyword" },
  ["@punctuation.delimiter"] = { fg = c.definition },
  ["@punctuation.bracket"]   = { fg = c.definition },
  ["@punctuation.special"]   = { fg = c.definition },

  ["@variable"]              = { link = "Identifier" },
  ["@variable.builtin"]      = { link = "Constant" },
  ["@variable.parameter"]    = { link = "Identifier" },
  ["@variable.member"]       = { link = "Identifier" },
  ["@property"]              = { link = "Identifier" },
  ["@attribute"]             = { link = "Keyword" },
  ["@module"]                = { link = "Structure" },

  ["@constant"]              = { link = "Constant" },
  ["@constant.builtin"]      = { link = "Constant" },
  ["@string"]                = { link = "String" },
  ["@string.regexp"]         = { link = "String" },
  ["@string.escape"]         = { link = "Special" },
  ["@string.special"]        = { link = "Special" },
  ["@character"]             = { link = "Character" },
  ["@number"]                = { link = "Number" },
  ["@boolean"]               = { link = "Boolean" },
  ["@constructor"]           = { link = "Identifier" },

  ["@tag"]                   = { link = "Keyword" },
  ["@tag.delimiter"]         = { link = "Keyword" },
  ["@tag.attribute"]         = { link = "Keyword" },

  ["@markup.heading"]        = { link = "Title" },
  ["@markup.italic"]         = { fg = c.text, italic = true },
  ["@markup.strong"]         = { fg = c.text, bold = true },
  ["@markup.link"]           = { link = "Underlined" },
  ["@markup.link.uri"]       = { link = "Underlined" },
  ["@markup.list"]           = { fg = c.constant },
  ["@markup.raw"]            = { link = "Constant" },
  ["@markup.quote"]          = { link = "Comment" },

  -- Diff / Git
  DiffAdd      = { bg = c.add },
  DiffChange   = { bg = c.change },
  DiffDelete   = { bg = c.delete },
  GitSignsAdd    = { fg = c.string },
  GitSignsChange = { fg = c.constant },
  GitSignsDelete = { fg = c.error },

  ["@text.diff.add"]    = { link = "DiffAdd" },
  ["@text.diff.delete"] = { link = "DiffDelete" },
  ["@diff.plus"]        = { link = "GitSignsAdd" },
  ["@diff.minus"]       = { link = "GitSignsDelete" },
  ["@diff.delta"]       = { link = "GitSignsChange" },

  -- Diagnostics
  DiagnosticError = { fg = c.error },
  DiagnosticWarn  = { fg = c.constant },
  DiagnosticHint  = { fg = c.comment },
  DiagnosticInfo  = { fg = c.text },

  -- Plugins
  BlinkCmpLabelMatch = { fg = c.constant },
}

for group, hl in pairs(groups) do
  vim.api.nvim_set_hl(0, group, hl)
end
