return {
  enabled = true,
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    -- delay = 100,
    preset = "helix",
    icons = {
      -- set icon mappings to false to disable distracting icons
      mappings = false,
      keys = {
        Up = "<Up> ",
        Down = "<Down> ",
        Left = "<Left> ",
        Right = "<Right> ",
        C = "<C-…> ",
        M = "<M-…> ",
        D = "<D-…> ",
        S = "<S-…> ",
        CR = "<CR> ",
        Esc = "<Esc> ",
        ScrollWheelDown = "<ScrollWheelDown> ",
        ScrollWheelUp = "<ScrollWheelUp> ",
        NL = "<NL> ",
        BS = "<BS> ",
        Space = "󱁐 ",
        Tab = "<Tab> ",
        F1 = "<F1>",
        F2 = "<F2>",
        F3 = "<F3>",
        F4 = "<F4>",
        F5 = "<F5>",
        F6 = "<F6>",
        F7 = "<F7>",
        F8 = "<F8>",
        F9 = "<F9>",
        F10 = "<F10>",
        F11 = "<F11>",
        F12 = "<F12>",
      },
    },
    win = {
      border = "double",
    },
    -- Document existing key chains
    spec = {
      -- { "<leader>c", group = "Code", mode = { "n", "x" } },
      { "<leader>d", group = "Document" },
      { "<leader>s", group = "Search" },
      { "<leader>f", group = "Find" },
      { "<leader>w", group = "Workspace" },
      { "<leader>t", group = "Toggle" },
      -- { "<leader>g", group = "Git", mode = { "n", "v" } },
    },
  },
}
