name: Auto PR from feature branches

on:
  push:
    branches:
      - 'feature/**'

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0     
          
      - name: Create or update PR
        uses: peter-evans/create-pull-request@v5
        with:
          base: main  
          head: ${{ github.ref_name }}  
          title: ${{ github.ref_name }}
          body: |
            This PR was opened automatically by GitHub Actions.

            • **Branch**: `${{ github.ref_name }}`  
            • **Commit**: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})  
          
          update-method: squash
          labels: automated
          token: ${{ secrets.GITHUB_TOKEN }}
