name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0     
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
